name: Deploy to S3 and CloudFront

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_ROLE_ARN: arn:aws:iam::279843290636:role/github-actions-deployer
  S3_BUCKET_NAME: navalnomad.com
  CLOUDFRONT_DISTRIBUTION_ID: E35VTEQJ8DGT8T

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          cache: 'npm'
          cache-dependency-path: landing/package-lock.json
      
      - name: Install dependencies
        run: |
          cd landing
          npm ci
      
      - name: Build
        run: |
          cd landing
          npm run build
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-1
      
      - name: Deploy to S3
        run: |
          aws s3 sync landing/dist/ s3://${{ env.S3_BUCKET_NAME }} --delete
      
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*" 