name: Deploy FrontendsInfrastructure

on:
  push:
    # branches: [ main ]
    paths: 
      - 'landing/infrastructure/frontend/**'
  workflow_dispatch:

env:
  AWS_ROLE_ARN: arn:aws:iam::279843290636:role/github-actions-deployer

permissions:
  contents: read
  id-token: write

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-1
      
      - name: Deploy Testing Infrastructure
        run: |
          cd landing/infrastructure/frontend
          tofu init -backend-config=environments/testing/backend.tfvars
          tofu plan -var-file=environments/testing/variables.tfvars
          tofu apply -auto-approve -var-file=environments/testing/variables.tfvars
      
      - name: Output Infrastructure Details
        run: |
          cd landing/infrastructure/frontend
          echo "S3 Bucket: $(tofu output -raw s3_bucket_name)"
          echo "CloudFront Distribution ID: $(tofu output -raw cloudfront_distribution_id)"
          echo "Testing URL: $(tofu output -raw preview_url)"
